travis:
  secure:
    BINSTAR_TOKEN: WU2mh/aq3LLIWBlsR8SSKQm6SIByp56F2f9Cg1usvd5HOzk4O9OdAHKebJwwn+LJRmtjiO12Lfu8KPMvquty4x12oemgRLV1FK7qek+V1OXg/IPZsQoF4c91q2SHM45adV/AVy12ljClXSN0dgQnbtp1VOtvN2/FDpLBWZ+gDIJd4g/S/OXJ5Mq2G88BlPJZCtri/dH0GaOs2Qpokb+KWSzeFw3aEvrke/bOF25kjJMMWnGBdDurXL8M+rul0/qqKooNVk/tkuVUW3ngXEjD+6yHYnouredzG2ja49O3QXKf2e6HcZhMDGj2z9gLDiWj134/I6cbmFSQGDZjKm0n1PP2d8fBvt6GAqLYrvB+q+xFtVpCOU8CB051q4Z6YlqXElP31dpD/1p3pBRn6YxBoSW6rdqeff99IxrCD3eR2giPSZe52AoLbS5+dcfoqOCX2BwgaRQfnCD50XXGaQN7nQXkix7MaQ2t4IFiUUSmuqxhdrajVus4kZwGUclrmVxYfea9hU33CWi2ZY8ixoRWbMIWtZbLqHx/HM7TLkmDQlTIu9oOSbpPPViUBiJaK71Yqcc/18sCDkbXyR1o67Dp6l2Dmdz2+v4QjD1porYkiE9kyxePfD6lteF7trfGhcmIFSFk29p8bWVIFFLrYNnQtSeaWKnE1ZVEcJmrzNCVYVY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
